// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTH50oQIF-tpFZs0vha4396DmX7_OrqIs',
    appId: '1:423467611101:web:placeholder',
    messagingSenderId: '423467611101',
    projectId: 'smart-notice-board-1922b',
    authDomain: 'smart-notice-board-1922b.firebaseapp.com',
    storageBucket: 'smart-notice-board-1922b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTH50oQIF-tpFZs0vha4396DmX7_OrqIs',
    appId: '1:423467611101:android:efac71709b6a69c1d43c34',
    messagingSenderId: '423467611101',
    projectId: 'smart-notice-board-1922b',
    storageBucket: 'smart-notice-board-1922b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTH50oQIF-tpFZs0vha4396DmX7_OrqIs',
    appId: '1:423467611101:android:efac71709b6a69c1d43c34', // Using Android ID as fallback for now
    messagingSenderId: '423467611101',
    projectId: 'smart-notice-board-1922b',
    storageBucket: 'smart-notice-board-1922b.firebasestorage.app',
  );
}
